# Generated by Django 5.0 on 2026-07-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🎯', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='⚡', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Build ATS-Friendly CVs in Minutes', max_length=200)),
                ('hero_subtitle', models.TextField(default='Tailored to the job requirements you care about.')),
                ('hero_cta_text', models.CharField(default='Create Your CV', max_length=80)),
                ('safety_notice', models.TextField(default='Your information stays in the current session and is not stored long term.')),
                ('features_title', models.CharField(default='Features', max_length=200)),
                ('features_subtitle', models.TextField(default='Everything you need to build a polished CV quickly.')),
                ('process_title', models.CharField(default='How it works', max_length=200)),
                ('process_subtitle', models.TextField(default='A simple five-step flow from input to download.')),
                ('benefits_title', models.CharField(default='What you get', max_length=200)),
                ('benefits_subtitle', models.TextField(default='A recruiter-friendly CV with relevant keywords and a clear layout.')),
                ('testimonials_title', models.CharField(default='What users say', max_length=200)),
                ('faq_title', models.CharField(default='Frequently asked questions', max_length=200)),
                ('footer_text', models.TextField(default='© 2026 CVGuide. Built for ATS-friendly CV creation.')),
            ],
            options={
                'verbose_name_plural': 'Landing Page Content',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
