# Generated by Django 5.0 on 2026-07-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('period', models.CharField(help_text='e.g., 2020 - 2024', max_length=100)),
                ('gpa_cgpa', models.CharField(blank=True, max_length=20, null=True)),
                ('gpa_max', models.CharField(blank=True, max_length=20, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('responsibilities', models.TextField(help_text='One responsibility per line')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('job_description', models.TextField()),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords', null=True)),
                ('required_skills', models.TextField(blank=True, help_text='Comma-separated required skills', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Machine Learning', 'Machine Learning'), ('Python', 'Python'), ('Django', 'Django'), ('Flask', 'Flask'), ('FastAPI', 'FastAPI'), ('ReactJS', 'ReactJS'), ('AngularJS', 'AngularJS'), ('VueJS', 'VueJS'), ('Event Management', 'Event Management'), ('Data Analysis', 'Data Analysis'), ('Web Scraping', 'Web Scraping'), ('Automation', 'Automation'), ('Backend Development', 'Backend Development'), ('Frontend Development', 'Frontend Development'), ('Full Stack', 'Full Stack'), ('Mobile Development', 'Mobile Development'), ('DevOps', 'DevOps'), ('Cloud Computing', 'Cloud Computing'), ('Cybersecurity', 'Cybersecurity'), ('Blockchain', 'Blockchain'), ('IoT', 'IoT'), ('Game Development', 'Game Development'), ('Desktop Application', 'Desktop Application'), ('Research', 'Research'), ('Academic Project', 'Academic Project'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Use bullet points (one per line)')),
                ('source_code_link', models.URLField(blank=True, null=True)),
                ('project_link', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Programming Languages', 'Programming Languages'), ('Machine Learning & AI', 'Machine Learning & AI'), ('Data Analysis & Visualization', 'Data Analysis & Visualization'), ('Databases', 'Databases'), ('Backend Development', 'Backend Development'), ('Frontend Development', 'Frontend Development'), ('Cloud & DevOps', 'Cloud & DevOps'), ('Web Scraping & Automation', 'Web Scraping & Automation'), ('Testing & QA', 'Testing & QA'), ('Project Management & Soft Skills', 'Project Management & Soft Skills')], max_length=100)),
                ('items', models.TextField(help_text='Comma-separated skills')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'id'],
            },
        ),
    ]
