# Generated by Django 5.0 on 2026-07-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0002_education_experience_jobrequirements_personalinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.CharField(help_text='e.g., Jan 2024', max_length=100)),
                ('expiration_date', models.CharField(blank=True, help_text="e.g., Jan 2027 or 'Does not expire'", max_length=100, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=200, null=True)),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Certifications',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HonorAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('date_received', models.CharField(help_text='e.g., June 2023', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of the honor/award', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Honor & Award',
                'verbose_name_plural': 'Honors & Awards',
                'ordering': ['order', 'id'],
            },
        ),
    ]
