DEFAULT_PROJECT_CATEGORIES = [
    'Machine Learning', 'Python', 'Django', 'Flask', 'FastAPI', 'ReactJS', 'AngularJS', 'VueJS',
    'Event Management', 'Data Analysis', 'Web Scraping', 'Automation', 'Backend Development',
    'Frontend Development', 'Full Stack', 'Mobile Development', 'DevOps', 'Cloud Computing',
    'Cybersecurity', 'Blockchain', 'IoT', 'Game Development', 'Desktop Application',
    'Research', 'Academic Project', 'Other'
]


DEFAULT_SKILL_CATEGORIES = [
    'Programming Languages',
    'Machine Learning & AI',
    'Data Analysis & Visualization',
    'Database Management',
    'Backend Development',
    'Frontend Development',
    'Cloud & Deployment',
    'DevOps & Infrastructure',
    'Web Scraping & Automation',
    'Dev Tools & IDEs',
    'Software Testing & QA',
    'Project Management & Soft Skills',
    'Mobile App Development',
    'Cybersecurity',
    'Data Engineering',
    'API Development & Integration',
    'UI/UX Design',
    'Game Development',
    'Blockchain & Web3',
    'Embedded Systems & IoT',
]


SKILL_KEYWORD_MAP = {
    'Programming Languages': [
        ('python', 'Python'),
        ('c++', 'C++'),
        ('c', 'C'),
        ('java', 'Java'),
        ('javascript', 'JavaScript'),
        (' js', 'JavaScript'),
        ('typescript', 'TypeScript'),
        ('php', 'PHP'),
        ('ruby', 'Ruby'),
        ('go', 'Go'),
        ('golang', 'Go'),
        ('kotlin', 'Kotlin'),
        ('swift', 'Swift'),
        ('sql', 'SQL'),
        ('bash', 'Bash'),
        ('shell', 'Shell'),
        ('r', 'R'),
        ('scala', 'Scala'),
        ('rust', 'Rust'),
        ('matlab', 'MATLAB'),
        ('dart', 'Dart'),
        ('lua', 'Lua'),
        ('perl', 'Perl'),
        ('objective-c', 'Objective-C'),
        ('c#', 'C#'),
        ('dotnet', '.NET'),
        ('vb.net', 'VB.NET'),
        ('f#', 'F#'),
        ('haskell', 'Haskell'),
        ('clojure', 'Clojure'),
        ('elixir', 'Elixir'),
        ('erlang', 'Erlang'),
    ],
    'Machine Learning & AI': [
        ('machine learning', 'Machine Learning'),
        ('ml', 'Machine Learning'),
        ('deep learning', 'Deep Learning'),
        ('artificial intelligence', 'Artificial Intelligence'),
        (' ai ', 'Artificial Intelligence'),
        ('scikit-learn', 'Scikit-learn'),
        ('sklearn', 'Scikit-learn'),
        ('tensorflow', 'TensorFlow'),
        ('pytorch', 'PyTorch'),
        ('keras', 'Keras'),
        ('feature engineering', 'Feature Engineering'),
        ('data preprocessing', 'Data Preprocessing'),
        ('feature scaling', 'Feature Scaling and Normalization'),
        ('normalization', 'Feature Scaling and Normalization'),
        ('hyperparameter tuning', 'Hyperparameter Tuning'),
        ('model validation', 'Model Validation'),
        ('mlops', 'MLOps'),
        ('ci/cd', 'CI / CD'),
        ('computer vision', 'Computer Vision'),
        ('cv', 'Computer Vision'),
        ('nlp', 'NLP'),
        ('natural language processing', 'NLP'),
        ('reinforcement learning', 'Reinforcement Learning'),
        ('xgboost', 'XGBoost'),
        ('lightgbm', 'LightGBM'),
        ('optuna', 'Optuna'),
        ('docker', 'Docker'),
        ('hugging face', 'Hugging Face'),
        ('transformers', 'Transformers'),
        ('bert', 'BERT'),
        ('gpt', 'GPT'),
        ('llm', 'Large Language Models'),
        ('large language model', 'Large Language Models'),
        ('generative ai', 'Generative AI'),
        ('rag', 'RAG'),
        ('retrieval augmented generation', 'RAG'),
        ('langchain', 'LangChain'),
        ('llama', 'LLaMA'),
        ('stable diffusion', 'Stable Diffusion'),
        ('gan', 'GAN'),
        ('generative adversarial network', 'GAN'),
        ('yolo', 'YOLO'),
        ('opencv', 'OpenCV'),
        ('mediapipe', 'MediaPipe'),
        ('onnx', 'ONNX'),
        ('model deployment', 'Model Deployment'),
        ('model serving', 'Model Serving'),
        ('tensorrt', 'TensorRT'),
        ('triton', 'Triton Inference Server'),
    ],
    'Data Analysis & Visualization': [
        ('pandas', 'Pandas'),
        ('numpy', 'NumPy'),
        ('matplotlib', 'Matplotlib'),
        ('seaborn', 'Seaborn'),
        ('tableau', 'Tableau'),
        ('power bi', 'Power BI'),
        ('powerbi', 'Power BI'),
        ('metabase', 'Metabase'),
        ('eda', 'EDA'),
        ('exploratory data analysis', 'EDA'),
        ('data analysis', 'Data Analysis'),
        ('analytics', 'Analytics'),
        ('visualization', 'Data Visualization'),
        ('plotly', 'Plotly'),
        ('ggplot', 'ggplot'),
        ('superset', 'Apache Superset'),
        ('looker', 'Looker'),
        ('redash', 'Redash'),
        ('grafana', 'Grafana'),
        ('kibana', 'Kibana'),
        ('excel', 'Excel'),
        ('spreadsheet', 'Spreadsheets'),
        ('pivot table', 'Pivot Tables'),
        ('vlookup', 'VLOOKUP'),
        ('dax', 'DAX'),
        ('power query', 'Power Query'),
        ('statistics', 'Statistics'),
        ('statistical analysis', 'Statistical Analysis'),
        ('hypothesis testing', 'Hypothesis Testing'),
        ('regression', 'Regression Analysis'),
        ('time series', 'Time Series Analysis'),
        ('forecasting', 'Forecasting'),
        ('cohort analysis', 'Cohort Analysis'),
        ('funnel analysis', 'Funnel Analysis'),
    ],
    'Database Management': [
        ('postgresql', 'PostgreSQL'),
        ('postgres', 'PostgreSQL'),
        ('mysql', 'MySQL'),
        ('mongodb', 'MongoDB'),
        ('mongo', 'MongoDB'),
        ('sqlite', 'SQLite'),
        ('nosql', 'NoSQL'),
        ('database', 'Databases'),
        ('sql', 'SQL'),
        ('redis', 'Redis'),
        ('cassandra', 'Cassandra'),
        ('dynamodb', 'DynamoDB'),
        ('oracle', 'Oracle'),
        ('snowflake', 'Snowflake'),
        ('bigquery', 'BigQuery'),
        ('redshift', 'Redshift'),
        ('clickhouse', 'ClickHouse'),
        ('elasticsearch', 'Elasticsearch'),
        ('solr', 'Solr'),
        ('neo4j', 'Neo4j'),
        ('graph database', 'Graph Database'),
        ('timeseries', 'Time Series Database'),
        ('influxdb', 'InfluxDB'),
        ('couchdb', 'CouchDB'),
        ('couchbase', 'Couchbase'),
        ('mariadb', 'MariaDB'),
        ('sql server', 'SQL Server'),
        ('tsql', 'T-SQL'),
        ('pl/sql', 'PL/SQL'),
        ('stored procedure', 'Stored Procedures'),
        ('database design', 'Database Design'),
        ('data modeling', 'Data Modeling'),
        ('er diagram', 'ER Diagram'),
        ('normalization', 'Database Normalization'),
        ('indexing', 'Database Indexing'),
        ('query optimization', 'Query Optimization'),
        ('acid', 'ACID Transactions'),
        ('replication', 'Database Replication'),
        ('sharding', 'Database Sharding'),
    ],
    'Backend Development': [
        ('django', 'Django'),
        ('drf', 'Django REST Framework'),
        ('django rest', 'Django REST Framework'),
        ('flask', 'Flask'),
        ('fastapi', 'FastAPI'),
        ('rest api', 'REST APIs'),
        ('restful', 'REST APIs'),
        ('api', 'API Development'),
        ('backend', 'Backend Development'),
        ('authentication', 'Authentication'),
        ('oauth', 'OAuth'),
        ('oauth2', 'OAuth2'),
        ('jwt', 'JWT'),
        ('json web token', 'JWT'),
        ('session', 'Session Management'),
        ('cookie', 'Cookie Management'),
        ('node.js', 'Node.js'),
        ('nodejs', 'Node.js'),
        ('express', 'Express.js'),
        ('expressjs', 'Express.js'),
        ('nestjs', 'NestJS'),
        ('koa', 'Koa'),
        ('spring boot', 'Spring Boot'),
        ('spring', 'Spring Framework'),
        ('graphql', 'GraphQL'),
        ('grpc', 'gRPC'),
        ('protocol buffers', 'Protocol Buffers'),
        ('protobuf', 'Protocol Buffers'),
        ('microservices', 'Microservices'),
        ('service mesh', 'Service Mesh'),
        ('istio', 'Istio'),
        ('linkerd', 'Linkerd'),
        ('message queue', 'Message Queues'),
        ('rabbitmq', 'RabbitMQ'),
        ('kafka', 'Apache Kafka'),
        ('pub/sub', 'Pub/Sub'),
        ('event driven', 'Event-Driven Architecture'),
        ('cqrs', 'CQRS'),
        ('event sourcing', 'Event Sourcing'),
        ('golang', 'Go'),
        ('gin', 'Gin'),
        ('echo', 'Echo'),
        ('fiber', 'Fiber'),
        ('laravel', 'Laravel'),
        ('symfony', 'Symfony'),
        ('codeigniter', 'CodeIgniter'),
        ('asp.net', 'ASP.NET Core'),
        ('dotnet core', 'ASP.NET Core'),
        ('entity framework', 'Entity Framework'),
        ('ruby on rails', 'Ruby on Rails'),
        ('rails', 'Ruby on Rails'),
    ],
    'Frontend Development': [
        ('react', 'React'),
        ('reactjs', 'React'),
        ('react.js', 'React'),
        ('next.js', 'Next.js'),
        ('nextjs', 'Next.js'),
        ('vue', 'Vue.js'),
        ('vuejs', 'Vue.js'),
        ('vue.js', 'Vue.js'),
        ('nuxt', 'Nuxt.js'),
        ('nuxtjs', 'Nuxt.js'),
        ('angular', 'Angular'),
        ('angularjs', 'AngularJS'),
        ('svelte', 'Svelte'),
        ('sveltekit', 'SvelteKit'),
        ('html', 'HTML'),
        ('css', 'CSS'),
        ('scss', 'SCSS'),
        ('sass', 'Sass'),
        ('less', 'Less'),
        ('tailwind', 'Tailwind CSS'),
        ('tailwindcss', 'Tailwind CSS'),
        ('bootstrap', 'Bootstrap'),
        ('material ui', 'Material UI'),
        ('mui', 'MUI'),
        ('chakra ui', 'Chakra UI'),
        ('ant design', 'Ant Design'),
        ('jest', 'Jest'),
        ('vitest', 'Vitest'),
        ('cypress', 'Cypress'),
        ('playwright', 'Playwright'),
        ('storybook', 'Storybook'),
        ('webpack', 'Webpack'),
        ('vite', 'Vite'),
        ('rollup', 'Rollup'),
        ('esbuild', 'esbuild'),
        ('parcel', 'Parcel'),
        ('babel', 'Babel'),
        ('typescript', 'TypeScript'),
        ('ts', 'TypeScript'),
        ('eslint', 'ESLint'),
        ('prettier', 'Prettier'),
        ('responsive design', 'Responsive Design'),
        ('web accessibility', 'Web Accessibility'),
        ('a11y', 'Accessibility'),
        ('wcag', 'WCAG'),
        ('pwa', 'Progressive Web Apps'),
        ('service worker', 'Service Workers'),
        ('web components', 'Web Components'),
        ('shadow dom', 'Shadow DOM'),
        ('canvas', 'Canvas API'),
        ('webgl', 'WebGL'),
        ('three.js', 'Three.js'),
        ('gsap', 'GSAP'),
        ('framer motion', 'Framer Motion'),
    ],
    'Cloud & Deployment': [
        ('aws', 'AWS'),
        ('amazon web services', 'AWS'),
        ('ec2', 'EC2'),
        ('s3', 'S3'),
        ('lambda', 'Lambda'),
        ('rds', 'RDS'),
        ('dynamodb', 'DynamoDB'),
        ('cloudfront', 'CloudFront'),
        ('cloudformation', 'CloudFormation'),
        ('cdk', 'AWS CDK'),
        ('gcp', 'Google Cloud Platform'),
        ('google cloud', 'Google Cloud Platform'),
        ('compute engine', 'Compute Engine'),
        ('cloud run', 'Cloud Run'),
        ('cloud functions', 'Cloud Functions'),
        ('firestore', 'Firestore'),
        ('pubsub', 'Pub/Sub'),
        ('bigquery', 'BigQuery'),
        ('azure', 'Azure'),
        ('microsoft azure', 'Azure'),
        ('azure functions', 'Azure Functions'),
        ('aks', 'AKS'),
        ('docker', 'Docker'),
        ('container', 'Containerization'),
        ('kubernetes', 'Kubernetes'),
        ('k8s', 'Kubernetes'),
        ('helm', 'Helm'),
        ('ci/cd', 'CI / CD'),
        ('continuous integration', 'Continuous Integration'),
        ('continuous deployment', 'Continuous Deployment'),
        ('deployment', 'Deployment'),
        ('render', 'Render'),
        ('vercel', 'Vercel'),
        ('netlify', 'Netlify'),
        ('supabase', 'Supabase'),
        ('mongodb atlas', 'MongoDB Atlas'),
        ('planetscale', 'PlanetScale'),
        ('neon', 'Neon'),
        ('railway', 'Railway'),
        ('fly.io', 'Fly.io'),
        ('heroku', 'Heroku'),
        ('digitalocean', 'DigitalOcean'),
        ('linode', 'Linode'),
        ('vultr', 'Vultr'),
        ('cloud', 'Cloud Computing'),
        ('terraform', 'Terraform'),
        ('infrastructure as code', 'Infrastructure as Code'),
        ('iac', 'Infrastructure as Code'),
        ('ansible', 'Ansible'),
        ('jenkins', 'Jenkins'),
        ('github actions', 'GitHub Actions'),
        ('gitlab ci', 'GitLab CI'),
        ('circleci', 'CircleCI'),
        ('travis ci', 'Travis CI'),
        ('argo cd', 'Argo CD'),
        ('flux', 'Flux'),
        ('prometheus', 'Prometheus'),
        ('grafana', 'Grafana'),
        ('datadog', 'Datadog'),
        ('new relic', 'New Relic'),
        ('sentry', 'Sentry'),
        ('elk stack', 'ELK Stack'),
        ('elastic stack', 'Elastic Stack'),
        ('loki', 'Loki'),
        ('tempo', 'Tempo'),
        ('jaeger', 'Jaeger'),
        ('zipkin', 'Zipkin'),
    ],
    'DevOps & Infrastructure': [
        ('devops', 'DevOps'),
        ('ci/cd', 'CI/CD'),
        ('pipeline', 'CI/CD Pipelines'),
        ('jenkins', 'Jenkins'),
        ('github actions', 'GitHub Actions'),
        ('gitlab ci', 'GitLab CI'),
        ('circleci', 'CircleCI'),
        ('travis', 'Travis CI'),
        ('argo', 'Argo'),
        ('tekton', 'Tekton'),
        ('spinnaker', 'Spinnaker'),
        ('terraform', 'Terraform'),
        ('pulumi', 'Pulumi'),
        ('ansible', 'Ansible'),
        ('chef', 'Chef'),
        ('puppet', 'Puppet'),
        ('saltstack', 'SaltStack'),
        ('kubernetes', 'Kubernetes'),
        ('k8s', 'Kubernetes'),
        ('helm', 'Helm'),
        ('kustomize', 'Kustomize'),
        ('operator', 'Kubernetes Operators'),
        ('istio', 'Istio'),
        ('linkerd', 'Linkerd'),
        ('consul', 'Consul'),
        ('vault', 'HashiCorp Vault'),
        ('nomad', 'Nomad'),
        ('docker', 'Docker'),
        ('containerd', 'containerd'),
        ('podman', 'Podman'),
        ('buildah', 'Buildah'),
        ('kaniko', 'Kaniko'),
        ('skaffold', 'Skaffold'),
        ('tilt', 'Tilt'),
        ('prometheus', 'Prometheus'),
        ('grafana', 'Grafana'),
        ('alertmanager', 'Alertmanager'),
        ('loki', 'Loki'),
        ('tempo', 'Tempo'),
        ('jaeger', 'Jaeger'),
        ('opentelemetry', 'OpenTelemetry'),
        ('elk', 'ELK Stack'),
        ('efk', 'EFK Stack'),
        ('datadog', 'Datadog'),
        ('new relic', 'New Relic'),
        ('sentry', 'Sentry'),
        ('pagerduty', 'PagerDuty'),
        ('opsgenie', 'Opsgenie'),
        ('linux', 'Linux'),
        ('bash', 'Bash Scripting'),
        ('shell scripting', 'Shell Scripting'),
        ('systemd', 'systemd'),
        ('nginx', 'NGINX'),
        ('apache', 'Apache HTTP Server'),
        ('haproxy', 'HAProxy'),
        ('traefik', 'Traefik'),
        ('envoy', 'Envoy Proxy'),
        ('dns', 'DNS'),
        ('ssl', 'SSL/TLS'),
        ('tls', 'SSL/TLS'),
        ('letsencrypt', 'Let\'s Encrypt'),
        ('cert-manager', 'cert-manager'),
    ],
    'Web Scraping & Automation': [
        ('web scraping', 'Web Scraping'),
        ('scraping', 'Web Scraping'),
        ('requests', 'Requests'),
        ('httpx', 'HTTPX'),
        ('aiohttp', 'aiohttp'),
        ('selenium', 'Selenium'),
        ('playwright', 'Playwright'),
        ('puppeteer', 'Puppeteer'),
        ('beautifulsoup', 'BeautifulSoup'),
        ('bs4', 'BeautifulSoup'),
        ('lxml', 'lxml'),
        ('scrapy', 'Scrapy'),
        ('automation', 'Automation'),
        ('bots', 'Automation Bots'),
        ('rpa', 'RPA'),
        ('robotic process automation', 'RPA'),
        ('zapier', 'Zapier'),
        ('n8n', 'n8n'),
        ('make', 'Make (Integromat)'),
        ('ifttt', 'IFTTT'),
        ('workflow automation', 'Workflow Automation'),
    ],
    'Dev Tools & IDEs': [
        ('git', 'Git'),
        ('github', 'GitHub'),
        ('gitlab', 'GitLab'),
        ('bitbucket', 'Bitbucket'),
        ('svn', 'SVN'),
        ('mercurial', 'Mercurial'),
        ('anaconda', 'Anaconda Navigator'),
        ('miniconda', 'Miniconda'),
        ('jupyter', 'Jupyter Notebook'),
        ('jupyterlab', 'JupyterLab'),
        ('colab', 'Google Colab'),
        ('kaggle', 'Kaggle'),
        ('visual studio', 'Visual Studio'),
        ('vscode', 'VS Code'),
        ('visual studio code', 'VS Code'),
        ('pycharm', 'PyCharm'),
        ('intellij', 'IntelliJ IDEA'),
        ('webstorm', 'WebStorm'),
        ('goland', 'GoLand'),
        ('rider', 'Rider'),
        ('clion', 'CLion'),
        ('phpstorm', 'PhpStorm'),
        ('datagrip', 'DataGrip'),
        ('vim', 'Vim'),
        ('neovim', 'Neovim'),
        ('emacs', 'Emacs'),
        ('sublime text', 'Sublime Text'),
        ('atom', 'Atom'),
        ('zed', 'Zed'),
        ('cursor', 'Cursor'),
        ('windsurf', 'Windsurf'),
        ('docker', 'Docker'),
        ('docker compose', 'Docker Compose'),
        ('podman', 'Podman'),
        ('make', 'Make'),
        ('cmake', 'CMake'),
        ('bazel', 'Bazel'),
        ('gradle', 'Gradle'),
        ('maven', 'Maven'),
        ('npm', 'npm'),
        ('yarn', 'Yarn'),
        ('pnpm', 'pnpm'),
        ('pip', 'pip'),
        ('poetry', 'Poetry'),
        ('pipenv', 'Pipenv'),
        ('conda', 'Conda'),
        ('uv', 'uv'),
        ('cargo', 'Cargo'),
        ('rustup', 'rustup'),
        ('nvm', 'nvm'),
        ('fnm', 'fnm'),
        ('asdf', 'asdf'),
        ('mise', 'mise'),
    ],
    'Software Testing & QA': [
        ('testing', 'Testing Fundamentals'),
        ('qa', 'Software Testing'),
        ('quality assurance', 'Quality Assurance'),
        ('pytest', 'Pytest'),
        ('unittest', 'unittest'),
        ('doctest', 'doctest'),
        ('nose', 'nose'),
        ('manual testing', 'Manual Testing'),
        ('automated testing', 'Automated Testing'),
        ('unit testing', 'Unit Testing'),
        ('integration testing', 'Integration Testing'),
        ('end to end testing', 'End-to-End Testing'),
        ('e2e testing', 'End-to-End Testing'),
        ('bug reporting', 'Bug Reporting'),
        ('test case', 'Test Case Design'),
        ('test plan', 'Test Planning'),
        ('selenium', 'Selenium Testing'),
        ('cypress', 'Cypress'),
        ('playwright', 'Playwright Testing'),
        ('puppeteer', 'Puppeteer Testing'),
        ('jest', 'Jest'),
        ('vitest', 'Vitest'),
        ('mocha', 'Mocha'),
        ('chai', 'Chai'),
        ('jasmine', 'Jasmine'),
        ('karma', 'Karma'),
        ('testcafe', 'TestCafe'),
        ('webdriverio', 'WebdriverIO'),
        ('nightwatch', 'Nightwatch'),
        ('codeceptjs', 'CodeceptJS'),
        ('robot framework', 'Robot Framework'),
        ('behave', 'Behave'),
        ('lettuce', 'Lettuce'),
        ('cucumber', 'Cucumber'),
        ('gherkin', 'Gherkin'),
        ('bdd', 'BDD'),
        ('tdd', 'TDD'),
        ('test driven development', 'TDD'),
        ('coverage', 'Code Coverage'),
        ('mutation testing', 'Mutation Testing'),
        ('property based testing', 'Property-Based Testing'),
        ('hypothesis', 'Hypothesis'),
        ('fuzzing', 'Fuzzing'),
        ('load testing', 'Load Testing'),
        ('performance testing', 'Performance Testing'),
        ('stress testing', 'Stress Testing'),
        ('jmeter', 'JMeter'),
        ('k6', 'k6'),
        ('locust', 'Locust'),
        ('gatling', 'Gatling'),
        ('vegeta', 'Vegeta'),
        ('contract testing', 'Contract Testing'),
        ('pact', 'Pact'),
        ('chaos engineering', 'Chaos Engineering'),
        ('litmus', 'Litmus'),
        ('gremlin', 'Gremlin'),
    ],
    'Project Management & Soft Skills': [
        ('agile', 'Agile'),
        ('scrum', 'Scrum'),
        ('kanban', 'Kanban'),
        ('jira', 'Jira'),
        ('confluence', 'Confluence'),
        ('trello', 'Trello'),
        ('notion', 'Notion'),
        ('asana', 'Asana'),
        ('monday.com', 'monday.com'),
        ('clickup', 'ClickUp'),
        ('linear', 'Linear'),
        ('github projects', 'GitHub Projects'),
        ('gitlab issues', 'GitLab Issues'),
        ('leadership', 'Leadership'),
        ('teamwork', 'Teamwork'),
        ('communication', 'Communication'),
        ('problem solving', 'Problem Solving'),
        ('documentation', 'Documentation'),
        ('mentoring', 'Mentoring'),
        ('coaching', 'Coaching'),
        ('code review', 'Code Review'),
        ('pair programming', 'Pair Programming'),
        ('technical writing', 'Technical Writing'),
        ('public speaking', 'Public Speaking'),
        ('presentation', 'Presentation Skills'),
        ('negotiation', 'Negotiation'),
        ('conflict resolution', 'Conflict Resolution'),
        ('time management', 'Time Management'),
        ('prioritization', 'Prioritization'),
        ('roadmap', 'Product Roadmap'),
        ('backlog', 'Backlog Management'),
        ('sprint planning', 'Sprint Planning'),
        ('retrospective', 'Retrospectives'),
        ('standup', 'Daily Standups'),
        ('estimation', 'Estimation'),
        ('story points', 'Story Points'),
        ('velocity', 'Velocity Tracking'),
        ('burndown', 'Burndown Charts'),
        ('release management', 'Release Management'),
        ('change management', 'Change Management'),
        ('stakeholder management', 'Stakeholder Management'),
        ('product management', 'Product Management'),
        ('project management', 'Project Management'),
        ('pmp', 'PMP'),
        ('prince2', 'PRINCE2'),
        ('safe', 'SAFe'),
        ('leads', 'LeSS'),
        ('scrum master', 'Scrum Master'),
        ('product owner', 'Product Owner'),
    ],
    'Mobile App Development': [
        ('mobile app development', 'Mobile App Development'),
        ('ios', 'iOS Development'),
        ('android', 'Android Development'),
        ('swift', 'Swift'),
        ('objective-c', 'Objective-C'),
        ('kotlin', 'Kotlin'),
        ('java', 'Java (Android)'),
        ('flutter', 'Flutter'),
        ('dart', 'Dart'),
        ('react native', 'React Native'),
        ('expo', 'Expo'),
        ('xamarin', 'Xamarin'),
        ('maui', '.NET MAUI'),
        ('ionic', 'Ionic'),
        ('capacitor', 'Capacitor'),
        ('cordova', 'Cordova'),
        ('phonegap', 'PhoneGap'),
        ('native script', 'NativeScript'),
        ('app store', 'App Store'),
        ('play store', 'Google Play Store'),
        ('testflight', 'TestFlight'),
        ('firebase', 'Firebase'),
        ('push notifications', 'Push Notifications'),
        ('in-app purchases', 'In-App Purchases'),
        ('mobile ui', 'Mobile UI/UX'),
        ('material design', 'Material Design'),
        ('human interface guidelines', 'Human Interface Guidelines'),
        ('swiftui', 'SwiftUI'),
        ('uikit', 'UIKit'),
        ('jetpack compose', 'Jetpack Compose'),
        ('xml layout', 'XML Layouts'),
        ('gradle', 'Gradle (Android)'),
        ('cocoapods', 'CocoaPods'),
        ('swift package manager', 'Swift Package Manager'),
        ('fastlane', 'Fastlane'),
        ('bitrise', 'Bitrise'),
        ('codemagic', 'Codemagic'),
        ('app center', 'App Center'),
    ],
    'Cybersecurity': [
        ('cybersecurity', 'Cybersecurity'),
        ('security', 'Information Security'),
        ('infosec', 'Information Security'),
        ('penetration testing', 'Penetration Testing'),
        ('pentest', 'Penetration Testing'),
        ('ethical hacking', 'Ethical Hacking'),
        ('vulnerability assessment', 'Vulnerability Assessment'),
        ('security audit', 'Security Auditing'),
        ('owasp', 'OWASP'),
        ('owasp top 10', 'OWASP Top 10'),
        ('xss', 'XSS'),
        ('sql injection', 'SQL Injection'),
        ('csrf', 'CSRF'),
        ('authentication', 'Authentication Security'),
        ('authorization', 'Authorization'),
        ('oauth', 'OAuth Security'),
        ('jwt security', 'JWT Security'),
        ('encryption', 'Encryption'),
        ('cryptography', 'Cryptography'),
        ('tls', 'TLS/SSL'),
        ('certificate', 'Certificate Management'),
        ('pki', 'PKI'),
        ('hashing', 'Hashing'),
        ('bcrypt', 'bcrypt'),
        ('argon2', 'Argon2'),
        ('scrypt', 'scrypt'),
        ('siem', 'SIEM'),
        ('soc', 'SOC'),
        ('incident response', 'Incident Response'),
        ('threat modeling', 'Threat Modeling'),
        ('secure coding', 'Secure Coding'),
        ('devsecops', 'DevSecOps'),
        ('sast', 'SAST'),
        ('dast', 'DAST'),
        ('iast', 'IAST'),
        ('sca', 'SCA'),
        ('dependency scanning', 'Dependency Scanning'),
        ('container security', 'Container Security'),
        ('kubernetes security', 'Kubernetes Security'),
        ('cloud security', 'Cloud Security'),
        ('iam', 'IAM'),
        ('rbac', 'RBAC'),
        ('abac', 'ABAC'),
        ('zero trust', 'Zero Trust'),
        ('mfa', 'MFA'),
        ('2fa', '2FA'),
        ('sso', 'SSO'),
        ('saml', 'SAML'),
        ('openid connect', 'OpenID Connect'),
        ('ldap', 'LDAP'),
        ('active directory', 'Active Directory'),
    ],
    'Data Engineering': [
        ('data engineering', 'Data Engineering'),
        ('etl', 'ETL'),
        ('elt', 'ELT'),
        ('data pipeline', 'Data Pipelines'),
        ('data warehouse', 'Data Warehousing'),
        ('data lake', 'Data Lake'),
        ('lakehouse', 'Lakehouse'),
        ('apache spark', 'Apache Spark'),
        ('pyspark', 'PySpark'),
        ('spark sql', 'Spark SQL'),
        ('databricks', 'Databricks'),
        ('apache airflow', 'Apache Airflow'),
        ('airflow', 'Apache Airflow'),
        ('prefect', 'Prefect'),
        ('dagster', 'Dagster'),
        ('luigi', 'Luigi'),
        ('kafka', 'Apache Kafka'),
        ('kafka streams', 'Kafka Streams'),
        ('ksql', 'ksqlDB'),
        ('flink', 'Apache Flink'),
        ('beam', 'Apache Beam'),
        ('pulsar', 'Apache Pulsar'),
        ('rabbitmq', 'RabbitMQ'),
        ('aws kinesis', 'AWS Kinesis'),
        ('google pubsub', 'Google Pub/Sub'),
        ('azure event hubs', 'Azure Event Hubs'),
        ('cdc', 'Change Data Capture'),
        ('debezium', 'Debezium'),
        ('maxwell', 'Maxwell'),
        ('dbt', 'dbt'),
        ('data build tool', 'dbt'),
        ('sqlmesh', 'SQLMesh'),
        ('data quality', 'Data Quality'),
        ('great expectations', 'Great Expectations'),
        ('soda', 'Soda'),
        ('data contracts', 'Data Contracts'),
        ('data governance', 'Data Governance'),
        ('data catalog', 'Data Catalog'),
        ('data lineage', 'Data Lineage'),
        ('amundsen', 'Amundsen'),
        ('datahub', 'DataHub'),
        ('atlan', 'Atlan'),
        ('collibra', 'Collibra'),
        ('alation', 'Alation'),
        ('feature store', 'Feature Store'),
        ('feast', 'Feast'),
        ('hopsworks', 'Hopsworks'),
        ('tecton', 'Tecton'),
        ('mlflow', 'MLflow'),
        ('dvc', 'DVC'),
        ('delta lake', 'Delta Lake'),
        ('iceberg', 'Apache Iceberg'),
        ('hudi', 'Apache Hudi'),
        ('parquet', 'Parquet'),
        ('avro', 'Avro'),
        ('orc', 'ORC'),
        ('protobuf', 'Protocol Buffers'),
    ],
    'API Development & Integration': [
        ('api development', 'API Development'),
        ('rest api', 'REST APIs'),
        ('restful', 'RESTful APIs'),
        ('graphql', 'GraphQL'),
        ('grpc', 'gRPC'),
        ('websocket', 'WebSockets'),
        ('webhooks', 'Webhooks'),
        ('api gateway', 'API Gateway'),
        ('kong', 'Kong'),
        ('apigee', 'Apigee'),
        ('aws api gateway', 'AWS API Gateway'),
        ('azure api management', 'Azure API Management'),
        ('google cloud endpoints', 'Google Cloud Endpoints'),
        ('rate limiting', 'Rate Limiting'),
        ('throttling', 'Throttling'),
        ('api versioning', 'API Versioning'),
        ('api documentation', 'API Documentation'),
        ('swagger', 'Swagger/OpenAPI'),
        ('openapi', 'OpenAPI'),
        ('redoc', 'ReDoc'),
        ('postman', 'Postman'),
        ('insomnia', 'Insomnia'),
        ('hoppscotch', 'Hoppscotch'),
        ('api testing', 'API Testing'),
        ('contract testing', 'Contract Testing'),
        ('pact', 'Pact'),
        ('schema registry', 'Schema Registry'),
        ('avro', 'Avro'),
        ('protobuf', 'Protocol Buffers'),
        ('oauth', 'OAuth'),
        ('oauth2', 'OAuth2'),
        ('openid connect', 'OpenID Connect'),
        ('jwt', 'JWT'),
        ('api key', 'API Keys'),
        ('mutual tls', 'mTLS'),
        ('integration', 'System Integration'),
        ('microservices', 'Microservices'),
        ('service mesh', 'Service Mesh'),
        ('event driven', 'Event-Driven Architecture'),
        ('message queue', 'Message Queues'),
        ('event streaming', 'Event Streaming'),
        ('cqrs', 'CQRS'),
        ('event sourcing', 'Event Sourcing'),
    ],
    'UI/UX Design': [
        ('ui design', 'UI Design'),
        ('ux design', 'UX Design'),
        ('user interface', 'User Interface Design'),
        ('user experience', 'User Experience Design'),
        ('figma', 'Figma'),
        ('sketch', 'Sketch'),
        ('adobe xd', 'Adobe XD'),
        ('framer', 'Framer'),
        ('invision', 'InVision'),
        ('zeplin', 'Zeplin'),
        ('abstract', 'Abstract'),
        ('prototyping', 'Prototyping'),
        ('wireframing', 'Wireframing'),
        ('user research', 'User Research'),
        ('usability testing', 'Usability Testing'),
        ('user testing', 'User Testing'),
        ('a/b testing', 'A/B Testing'),
        ('design system', 'Design Systems'),
        ('design tokens', 'Design Tokens'),
        ('accessibility', 'Accessibility'),
        ('a11y', 'Accessibility'),
        ('wcag', 'WCAG'),
        ('responsive design', 'Responsive Design'),
        ('mobile first', 'Mobile-First Design'),
        ('design thinking', 'Design Thinking'),
        ('journey mapping', 'Journey Mapping'),
        ('personas', 'Personas'),
        ('information architecture', 'Information Architecture'),
        ('interaction design', 'Interaction Design'),
        ('visual design', 'Visual Design'),
        ('typography', 'Typography'),
        ('color theory', 'Color Theory'),
        ('iconography', 'Iconography'),
        ('illustration', 'Illustration'),
        ('motion design', 'Motion Design'),
        ('animation', 'Animation'),
        ('microinteractions', 'Microinteractions'),
        ('lottie', 'Lottie'),
        ('after effects', 'After Effects'),
        ('principle', 'Principle'),
        ('proto.io', 'Proto.io'),
        ('marvel', 'Marvel App'),
        ('balsamiq', 'Balsamiq'),
        ('mural', 'Mural'),
        ('miro', 'Miro'),
    ],
    'Game Development': [
        ('game development', 'Game Development'),
        ('unity', 'Unity'),
        ('unreal engine', 'Unreal Engine'),
        ('ue4', 'Unreal Engine 4'),
        ('ue5', 'Unreal Engine 5'),
        ('godot', 'Godot'),
        ('cocos2d', 'Cocos2d'),
        ('phaser', 'Phaser'),
        ('pixi.js', 'PixiJS'),
        ('three.js', 'Three.js'),
        ('babylon.js', 'Babylon.js'),
        ('c#', 'C# (Unity)'),
        ('c++', 'C++ (Unreal)'),
        ('blueprints', 'Blueprints (Unreal)'),
        ('gdscript', 'GDScript'),
        ('game design', 'Game Design'),
        ('level design', 'Level Design'),
        ('gameplay programming', 'Gameplay Programming'),
        ('graphics programming', 'Graphics Programming'),
        ('shader', 'Shader Programming'),
        ('hlsl', 'HLSL'),
        ('glsl', 'GLSL'),
        ('rendering', 'Rendering'),
        ('physics engine', 'Physics Engines'),
        ('havok', 'Havok'),
        ('physx', 'PhysX'),
        ('bullet physics', 'Bullet Physics'),
        ('ai in games', 'Game AI'),
        ('behavior trees', 'Behavior Trees'),
        ('state machines', 'State Machines'),
        ('navigation mesh', 'NavMesh'),
        ('multiplayer', 'Multiplayer Networking'),
        ('photon', 'Photon'),
        ('mirror', 'Mirror'),
        ('netcode', 'Netcode'),
        ('rollback', 'Rollback Netcode'),
        ('dedicated server', 'Dedicated Servers'),
        ('matchmaking', 'Matchmaking'),
        ('leaderboard', 'Leaderboards'),
        ('game analytics', 'Game Analytics'),
        ('unity analytics', 'Unity Analytics'),
        ('game monetization', 'Game Monetization'),
        ('in-app purchase', 'In-App Purchases'),
        ('ads mediation', 'Ads Mediation'),
        ('app store', 'App Store Connect'),
        ('play console', 'Google Play Console'),
        ('steamworks', 'Steamworks'),
        ('itch.io', 'itch.io'),
        ('game jam', 'Game Jams'),
    ],
    'Blockchain & Web3': [
        ('blockchain', 'Blockchain'),
        ('web3', 'Web3'),
        ('ethereum', 'Ethereum'),
        ('bitcoin', 'Bitcoin'),
        ('solidity', 'Solidity'),
        ('vyper', 'Vyper'),
        ('rust', 'Rust (Solana)'),
        ('solana', 'Solana'),
        ('anchor', 'Anchor'),
        ('cosmwasm', 'CosmWasm'),
        ('polkadot', 'Polkadot'),
        ('substrate', 'Substrate'),
        ('ink', 'ink!'),
        ('near', 'NEAR'),
        ('avalanche', 'Avalanche'),
        ('polygon', 'Polygon'),
        ('arbitrum', 'Arbitrum'),
        ('optimism', 'Optimism'),
        ('base', 'Base'),
        ('zksync', 'zkSync'),
        ('starknet', 'StarkNet'),
        ('smart contracts', 'Smart Contracts'),
        ('defi', 'DeFi'),
        ('nft', 'NFTs'),
        ('erc20', 'ERC-20'),
        ('erc721', 'ERC-721'),
        ('erc1155', 'ERC-1155'),
        ('dao', 'DAOs'),
        ('governance', 'Governance'),
        ('tokenomics', 'Tokenomics'),
        ('web3.js', 'web3.js'),
        ('ethers.js', 'ethers.js'),
        ('viem', 'viem'),
        ('wagmi', 'wagmi'),
        ('rainbowkit', 'RainbowKit'),
        ('walletconnect', 'WalletConnect'),
        ('metamask', 'MetaMask'),
        ('hardhat', 'Hardhat'),
        ('foundry', 'Foundry'),
        ('truffle', 'Truffle'),
        ('brownie', 'Brownie'),
        ('slither', 'Slither'),
        ('mythril', 'Mythril'),
        ('echidna', 'Echidna'),
        ('fuzzing', 'Smart Contract Fuzzing'),
        ('formal verification', 'Formal Verification'),
        ('zero knowledge', 'Zero Knowledge Proofs'),
        ('zk snark', 'zk-SNARKs'),
        ('zk stark', 'zk-STARKs'),
        ('plonk', 'PLONK'),
        ('circuit', 'Circuit Programming'),
        ('circom', 'Circom'),
        ('noir', 'Noir'),
        ('risc zero', 'RISC Zero'),
        ('sp1', 'SP1'),
    ],
    'Embedded Systems & IoT': [
        ('embedded systems', 'Embedded Systems'),
        ('iot', 'Internet of Things'),
        ('internet of things', 'IoT'),
        ('microcontroller', 'Microcontrollers'),
        ('mcu', 'MCU'),
        ('arm', 'ARM'),
        ('cortex-m', 'Cortex-M'),
        ('stm32', 'STM32'),
        ('esp32', 'ESP32'),
        ('esp8266', 'ESP8266'),
        ('arduino', 'Arduino'),
        ('raspberry pi', 'Raspberry Pi'),
        ('pico', 'Raspberry Pi Pico'),
        ('rp2040', 'RP2040'),
        ('nrf52', 'nRF52'),
        ('zephyr', 'Zephyr RTOS'),
        ('freertos', 'FreeRTOS'),
        ('threadx', 'ThreadX'),
        ('rtos', 'RTOS'),
        ('bare metal', 'Bare Metal Programming'),
        ('c', 'C (Embedded)'),
        ('c++', 'C++ (Embedded)'),
        ('rust', 'Rust (Embedded)'),
        ('assembly', 'Assembly'),
        ('gpio', 'GPIO'),
        ('i2c', 'I2C'),
        ('spi', 'SPI'),
        ('uart', 'UART'),
        ('can', 'CAN Bus'),
        ('usb', 'USB'),
        ('ethernet', 'Ethernet'),
        ('wifi', 'WiFi'),
        ('bluetooth', 'Bluetooth'),
        ('ble', 'Bluetooth Low Energy'),
        ('zigbee', 'Zigbee'),
        ('z-wave', 'Z-Wave'),
        ('lora', 'LoRa'),
        ('lorawan', 'LoRaWAN'),
        ('mqtt', 'MQTT'),
        ('coap', 'CoAP'),
        ('http', 'HTTP'),
        ('websocket', 'WebSocket'),
        ('sensor', 'Sensors'),
        ('actuator', 'Actuators'),
        ('adc', 'ADC'),
        ('dac', 'DAC'),
        ('pwm', 'PWM'),
        ('interrupt', 'Interrupts'),
        ('dma', 'DMA'),
        ('rtc', 'RTC'),
        ('watchdog', 'Watchdog Timer'),
        ('bootloader', 'Bootloaders'),
        ('dfu', 'DFU'),
        ('ota', 'OTA Updates'),
        ('firmware', 'Firmware Development'),
        ('device driver', 'Device Drivers'),
        ('kernel', 'Kernel Development'),
        ('linux kernel', 'Linux Kernel'),
        ('yocto', 'Yocto Project'),
        ('buildroot', 'Buildroot'),
        ('openwrt', 'OpenWrt'),
        ('pcb design', 'PCB Design'),
        ('kicad', 'KiCad'),
        ('eagle', 'EAGLE'),
        ('altium', 'Altium Designer'),
        ('easyeda', 'EasyEDA'),
        ('schematic', 'Schematic Capture'),
        ('layout', 'PCB Layout'),
    ],
}